"""add report_history table

Revision ID: 1628c2bb14b1
Revises: 4f2a79a497b2
Create Date: 2026-05-12 00:23:36.092170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1628c2bb14b1'
down_revision: Union[str, Sequence[str], None] = '4f2a79a497b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_report_history_client_id'), 'report_history', ['client_id'], unique=False)
    op.create_index(op.f('ix_report_history_id'), 'report_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_client_access_id'), 'user_client_access', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_client_access_id'), table_name='user_client_access')
    op.drop_index(op.f('ix_report_history_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_client_id'), table_name='report_history')
    op.alter_column('report_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
