"""add report_history table

Revision ID: 1628c2bb14b1
Revises: 4f2a79a497b2
Create Date: 2026-05-12 00:23:36.092170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1628c2bb14b1'
down_revision: Union[str, Sequence[str], None] = '4f2a79a497b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('report_type', sa.String(), nullable=False),
        sa.Column('period_days', sa.Integer(), nullable=False),
        sa.Column('objective', sa.String(), nullable=True),
        sa.Column('ad_account_id', sa.String(), nullable=True),
        sa.Column('campaign_ids', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_client_id'), 'report_history', ['client_id'], unique=False)
    op.create_index(op.f('ix_report_history_id'), 'report_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_client_access_id'), 'user_client_access', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_client_access_id'), table_name='user_client_access')
    op.drop_index(op.f('ix_report_history_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_client_id'), table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
