"""Add StoryArchive table

Revision ID: 89d8d9f5474e
Revises: 0001_init
Create Date: 2026-04-24 23:10:54.003351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d8d9f5474e'
down_revision: Union[str, Sequence[str], None] = '0001_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('taps_forward', sa.Integer(), nullable=True),
    sa.Column('taps_back', sa.Integer(), nullable=True),
    sa.Column('exits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_archive_client_id'), 'story_archive', ['client_id'], unique=False)
    op.create_index(op.f('ix_story_archive_id'), 'story_archive', ['id'], unique=False)
    op.create_index(op.f('ix_story_archive_story_id'), 'story_archive', ['story_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_archive_story_id'), table_name='story_archive')
    op.drop_index(op.f('ix_story_archive_id'), table_name='story_archive')
    op.drop_index(op.f('ix_story_archive_client_id'), table_name='story_archive')
    op.drop_table('story_archive')
    # ### end Alembic commands ###
