"""Add Audience and Media archives

Revision ID: c18de29d696a
Revises: 89d8d9f5474e
Create Date: 2026-04-25 10:46:06.739133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18de29d696a'
down_revision: Union[str, Sequence[str], None] = '89d8d9f5474e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('gender_age_json', sa.Text(), nullable=True),
    sa.Column('city_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_archive_client_id'), 'audience_archive', ['client_id'], unique=False)
    op.create_index(op.f('ix_audience_archive_id'), 'audience_archive', ['id'], unique=False)
    op.create_index(op.f('ix_audience_archive_snapshot_date'), 'audience_archive', ['snapshot_date'], unique=False)
    op.create_table('media_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_archive_client_id'), 'media_archive', ['client_id'], unique=False)
    op.create_index(op.f('ix_media_archive_id'), 'media_archive', ['id'], unique=False)
    op.create_index(op.f('ix_media_archive_media_id'), 'media_archive', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_archive_snapshot_date'), 'media_archive', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_archive_snapshot_date'), table_name='media_archive')
    op.drop_index(op.f('ix_media_archive_media_id'), table_name='media_archive')
    op.drop_index(op.f('ix_media_archive_id'), table_name='media_archive')
    op.drop_index(op.f('ix_media_archive_client_id'), table_name='media_archive')
    op.drop_table('media_archive')
    op.drop_index(op.f('ix_audience_archive_snapshot_date'), table_name='audience_archive')
    op.drop_index(op.f('ix_audience_archive_id'), table_name='audience_archive')
    op.drop_index(op.f('ix_audience_archive_client_id'), table_name='audience_archive')
    op.drop_table('audience_archive')
    # ### end Alembic commands ###
